-- Create activity_notes table
create table activity_notes (
  id bigint generated by default as identity primary key,
  activity_id uuid references activities(activity_id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by text default 'משתמש מערכת'
);

-- Enable RLS
alter table activity_notes enable row level security;

-- Create policy
create policy "Enable all access for all users" on activity_notes
  for all using (true) with check (true);
